# Generated by Django 2.2.14 on 2020-08-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_location_stores"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="address",),
        migrations.RemoveField(model_name="location", name="state",),
        migrations.RemoveField(model_name="location", name="zip",),
        migrations.RemoveField(model_name="stores", name="name",),
    ]
