# Generated by Django 2.2.14 on 2020-08-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200819_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lokation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=256)),
                ('address2', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=5)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storez_inventory', to='home.Inventory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storez_location', to='home.Lokation')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storez_name', to='home.Name')),
            ],
        ),
    ]
