# Generated by Django 2.2.14 on 2020-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200819_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='storez',
            name='contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
